name: Lint C# Code

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1' # You can change this version to your desired .NET version

    - name: Install dotnet format tool
      run: dotnet tool install -g dotnet-format --version 5.0.18303

    - name: Run dotnet format
      run: dotnet format --check --verbosity diagnostic ${{ github.workspace }}
